import { AIInsight } from "@/types";

export const mockInsights: AIInsight[] = [
  { id: "ai-001", type: "revenue", title: "Revenue trending 12% above Q1 forecast", description: "Based on current trajectory, March revenue will exceed projections by $178K. Consider increasing inventory for top-selling products to maintain momentum.", impact: "high", actionLabel: "View Revenue Forecast", createdAt: "2026-03-28T08:00:00Z" },
  { id: "ai-002", type: "churn", title: "3 accounts at risk of churning", description: "Valley Produce Partners, Blue Ridge Beverages, and Redwood Paper Products show declining order frequency. Valley Produce hasn't ordered in 45 days (avg: 7 days).", impact: "high", actionLabel: "View At-Risk Accounts", createdAt: "2026-03-28T07:30:00Z" },
  { id: "ai-003", type: "inventory", title: "Optimal reorder point for SKU-4421", description: "Based on demand patterns, Kraft Paper Rolls should be reordered by Thursday to avoid stockout. Current stock: 12 units, predicted weekly demand: 45 units.", impact: "high", actionLabel: "Create Purchase Order", createdAt: "2026-03-28T07:00:00Z" },
  { id: "ai-004", type: "lead", title: "Lead score for ABC Foods increased 22%", description: "ABC Foods International engagement signals spiked: opened 3 emails, visited pricing page twice, and connected on LinkedIn. Score: 87 (was 65).", impact: "medium", actionLabel: "View Lead Profile", createdAt: "2026-03-27T16:00:00Z" },
  { id: "ai-005", type: "email", title: "3 cold email sequences have <2% reply rate", description: "Restaurant Suppliers Holiday Prep, Tri-State Paper outreach, and Heartland Grain follow-up are underperforming. Consider A/B testing subject lines or pausing.", impact: "medium", actionLabel: "Review Sequences", createdAt: "2026-03-27T14:00:00Z" },
  { id: "ai-006", type: "optimization", title: "Optimal send time: Tuesday 9:15 AM", description: "Analysis of 2,400+ emails shows highest open rates on Tuesday mornings between 9-10 AM EST. Current campaigns send at 8 AM — shifting could improve opens by 18%.", impact: "medium", actionLabel: "Update Schedule", createdAt: "2026-03-27T12:00:00Z" },
  { id: "ai-007", type: "revenue", title: "Top 5 underperforming products identified", description: "Solvent Grade A, Ice Cream 3gal, Wire 14ga, PVC Pipe, and Copy Paper show declining margins despite steady volume. Recommend renegotiating supplier pricing.", impact: "medium", actionLabel: "View Products", createdAt: "2026-03-27T10:00:00Z" },
  { id: "ai-008", type: "alert", title: "Supplier lead time spike detected", description: "Pacific Trade Inc. average lead time increased 23% this month (from 7 to 8.6 days). This affects 15 products across 3 categories. Consider alternative suppliers.", impact: "high", actionLabel: "View Suppliers", createdAt: "2026-03-27T09:00:00Z" },
  { id: "ai-009", type: "lead", title: "Apex Industrial contract expiring in 60 days", description: "Their current supplier contract expires May 27. Derek Johnson showed high engagement. This is a $520K opportunity — recommend prioritizing outreach.", impact: "high", actionLabel: "View Deal", createdAt: "2026-03-26T15:00:00Z" },
  { id: "ai-010", type: "optimization", title: "Cross-sell opportunity: Packaging + Food accounts", description: "8 food distribution customers don't purchase packaging from us. Estimated incremental revenue: $180K/year based on industry benchmarks.", impact: "medium", actionLabel: "View Opportunities", createdAt: "2026-03-26T11:00:00Z" },
  { id: "ai-011", type: "churn", title: "Customer payment pattern anomaly", description: "Harbor Industries payment velocity slowed 40% this quarter. Outstanding balance: $67,800 (credit limit: $175,000). Payment score dropped from 85 to 78.", impact: "medium", actionLabel: "Review Account", createdAt: "2026-03-26T09:00:00Z" },
  { id: "ai-012", type: "inventory", title: "Seasonal demand spike predicted", description: "Based on prior year data, building materials demand will increase 35% in April. Current stock levels for cement and lumber may be insufficient.", impact: "high", actionLabel: "Review Inventory", createdAt: "2026-03-25T14:00:00Z" },
  { id: "ai-013", type: "email", title: "Subject line A/B test winner found", description: "\"Bulk pricing that beats your current supplier\" outperformed \"Special wholesale rates inside\" by 42% in open rate. Recommend using winning variant across campaigns.", impact: "low", actionLabel: "Apply to Campaigns", createdAt: "2026-03-25T10:00:00Z" },
  { id: "ai-014", type: "optimization", title: "Pipeline bottleneck: Proposal stage", description: "Average time in 'Proposal Sent' stage is 8.2 days — 60% longer than industry benchmark. 4 deals totaling $1.1M are stuck. Recommend follow-up cadence review.", impact: "high", actionLabel: "View Pipeline", createdAt: "2026-03-25T08:00:00Z" },
  { id: "ai-015", type: "revenue", title: "Meta Ads ROAS exceeding benchmark", description: "Food Wholesale Lead Gen campaign is delivering 8.2x ROAS vs 4.5x industry average. Consider scaling budget by 20% while performance holds.", impact: "medium", actionLabel: "View Campaign", createdAt: "2026-03-24T16:00:00Z" },
  { id: "ai-016", type: "alert", title: "Duplicate supplier invoices detected", description: "2 potential duplicate invoices from Global Supply Co. totaling $12,400. Amounts and dates match within 48 hours. Manual review recommended.", impact: "medium", actionLabel: "Review Invoices", createdAt: "2026-03-24T11:00:00Z" },
];
