import { Lead } from "@/types";

export const mockLeads: Lead[] = [
  { id: "lead-001", companyName: "ABC Foods International", contactName: "Michael Torres", email: "michael@abcfoods.com", phone: "(415) 555-3001", linkedIn: "linkedin.com/in/mtorres", website: "abcfoods.com", industry: "Food Distribution", location: "San Francisco, CA", employeeCount: 250, estimatedRevenue: 45000000, score: 87, status: "Hot", source: "AI Scraper", assignedRep: "Sarah Mitchell", tags: ["High Value", "Food"], enrichedData: { techStack: ["SAP", "Salesforce", "Shopify"], recentNews: ["Expanded to 3 new markets in Q1"], fundingStage: "Series C" }, createdAt: "2026-03-20T10:00:00Z", lastContactedAt: "2026-03-26T14:00:00Z" },
  { id: "lead-002", companyName: "BuildRight Construction", contactName: "Karen Phillips", email: "karen@buildright.com", phone: "(312) 555-3002", linkedIn: "linkedin.com/in/kphillips", website: "buildright.com", industry: "Construction", location: "Chicago, IL", employeeCount: 180, estimatedRevenue: 32000000, score: 74, status: "Warm", source: "Cold Email", assignedRep: "Mike Thompson", tags: ["Construction"], enrichedData: { techStack: ["Oracle", "Procore"], recentNews: ["Won $12M government contract"], fundingStage: "Private" }, createdAt: "2026-03-18T09:00:00Z", lastContactedAt: "2026-03-24T11:00:00Z" },
  { id: "lead-003", companyName: "FreshDirect Wholesale", contactName: "Jason Lee", email: "jason@freshdirectws.com", phone: "(212) 555-3003", website: "freshdirectws.com", industry: "Produce", location: "New York, NY", employeeCount: 95, estimatedRevenue: 18000000, score: 92, status: "Hot", source: "Meta Ads", assignedRep: "Sarah Mitchell", tags: ["Organic", "Urgent"], enrichedData: { techStack: ["NetSuite", "Slack"], recentNews: ["Looking for new bulk supplier per LinkedIn post"], fundingStage: "Series B" }, createdAt: "2026-03-22T08:30:00Z", lastContactedAt: "2026-03-27T09:00:00Z" },
  { id: "lead-004", companyName: "Sterling Packaging Group", contactName: "Amanda Wright", email: "amanda@sterlingpkg.com", phone: "(214) 555-3004", website: "sterlingpkg.com", industry: "Packaging", location: "Dallas, TX", employeeCount: 320, estimatedRevenue: 58000000, score: 65, status: "Warm", source: "Referral", tags: ["Packaging", "Enterprise"], enrichedData: { techStack: ["Microsoft Dynamics", "Power BI"], recentNews: ["Acquired competitor last quarter"], fundingStage: "Private" }, createdAt: "2026-03-15T14:00:00Z" },
  { id: "lead-005", companyName: "Mountain View Catering", contactName: "Roberto Garcia", email: "roberto@mvccatering.com", phone: "(303) 555-3005", website: "mvccatering.com", industry: "Catering", location: "Denver, CO", employeeCount: 45, estimatedRevenue: 5200000, score: 58, status: "Warm", source: "Website", tags: ["Small"], createdAt: "2026-03-21T16:00:00Z" },
  { id: "lead-006", companyName: "Pacific Rim Trading", contactName: "Yuki Nakamura", email: "yuki@pacificrimtrade.com", phone: "(206) 555-3006", website: "pacificrimtrade.com", industry: "Import/Export", location: "Seattle, WA", employeeCount: 150, estimatedRevenue: 28000000, score: 81, status: "Hot", source: "AI Scraper", assignedRep: "David Lee", tags: ["International", "High Value"], enrichedData: { techStack: ["SAP", "Tableau"], recentNews: ["New warehouse opened in Portland"], fundingStage: "Private" }, createdAt: "2026-03-19T11:00:00Z", lastContactedAt: "2026-03-25T15:00:00Z" },
  { id: "lead-007", companyName: "Heartland Grain Co.", contactName: "Bob Williams", email: "bob@heartlandgrain.com", phone: "(515) 555-3007", website: "heartlandgrain.com", industry: "Agriculture", location: "Des Moines, IA", employeeCount: 80, estimatedRevenue: 22000000, score: 42, status: "Cold", source: "Trade Show", tags: ["Agriculture"], createdAt: "2026-03-10T09:00:00Z" },
  { id: "lead-008", companyName: "Coastal Beverage Distributors", contactName: "Nicole Adams", email: "nicole@coastalbev.com", phone: "(305) 555-3008", website: "coastalbev.com", industry: "Beverages", location: "Miami, FL", employeeCount: 200, estimatedRevenue: 35000000, score: 78, status: "Warm", source: "Cold Email", assignedRep: "Alex Rivera", tags: ["Beverages", "Growing"], enrichedData: { techStack: ["HubSpot", "Shopify Plus"], recentNews: ["Hiring 50+ distribution staff"], fundingStage: "Series A" }, createdAt: "2026-03-17T13:00:00Z", lastContactedAt: "2026-03-23T10:00:00Z" },
  { id: "lead-009", companyName: "Apex Industrial Solutions", contactName: "Derek Johnson", email: "derek@apexindustrial.com", phone: "(713) 555-3009", website: "apexindustrial.com", industry: "Industrial Supply", location: "Houston, TX", employeeCount: 420, estimatedRevenue: 72000000, score: 88, status: "Hot", source: "AI Scraper", assignedRep: "Mike Thompson", tags: ["Enterprise", "Industrial", "High Priority"], enrichedData: { techStack: ["Oracle", "Salesforce", "ServiceNow"], recentNews: ["Current supplier contract expiring in 60 days"], fundingStage: "Public" }, createdAt: "2026-03-23T07:00:00Z", lastContactedAt: "2026-03-27T16:00:00Z" },
  { id: "lead-010", companyName: "Green Earth Organics", contactName: "Sophie Chen", email: "sophie@greenearthorg.com", phone: "(503) 555-3010", website: "greenearthorg.com", industry: "Organic Foods", location: "Portland, OR", employeeCount: 60, estimatedRevenue: 8500000, score: 71, status: "Warm", source: "Meta Ads", tags: ["Organic"], createdAt: "2026-03-24T12:00:00Z" },
  { id: "lead-011", companyName: "Tri-State Paper Products", contactName: "Mark Davis", email: "mark@tristatepaper.com", phone: "(609) 555-3011", website: "tristatepaper.com", industry: "Paper & Packaging", location: "Trenton, NJ", employeeCount: 110, estimatedRevenue: 15000000, score: 35, status: "Cold", source: "Cold Email", tags: ["Paper"], createdAt: "2026-03-12T10:00:00Z" },
  { id: "lead-012", companyName: "Southwest Chemical Corp", contactName: "Diana Martinez", email: "diana@swchemcorp.com", phone: "(602) 555-3012", website: "swchemcorp.com", industry: "Chemicals", location: "Phoenix, AZ", employeeCount: 175, estimatedRevenue: 41000000, score: 83, status: "Hot", source: "Referral", assignedRep: "David Lee", tags: ["Chemicals", "Warm Intro"], enrichedData: { techStack: ["SAP", "Tableau", "Monday.com"], recentNews: ["Seeking new bulk chemical supplier"], fundingStage: "Private" }, createdAt: "2026-03-25T09:00:00Z", lastContactedAt: "2026-03-27T11:00:00Z" },
];
